name: 'Custom Autograding Grader'
description: 'Runs a test script and emits a partial score for GitHub Classroom.'
runs:
  using: "composite"
  steps:
    - id: setup
      shell: bash
      run: ./.github/actions/custom-grader/setup.sh
    - id: run
      shell: bash
      run: ./.github/actions/custom-grader/score-tests.sh #"${{ inputs.command }}" "${{ inputs.test-name }}"
outputs:
  result:
    description: "JSON result for autograding reporter"
    value: ${{ steps.run.outputs.result }}
